vich_uploader:
  db_driver: orm

  mappings:
    mangas:
      uri_prefix: /images/mangas
      upload_destination: '%kernel.project_dir%/public/images/mangas'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
